config/routes.rb
Rails.application.routes.draw do

  resources :powerstats

  get 'pages/Index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#Index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/powerstat.rb
class Powerstat < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Index
  end
end

app/controllers/powerstats_controller.rb
class PowerstatsController < ApplicationController

  def index
    @powerstats = Powerstat.all
  end

  def show
    @powerstat = Powerstat.find(params[:id])
  end

  def new

  end

  def edit
    @powerstat = Powerstat.find(params[:id])
  end

  def create
    @powerstat = Powerstat.new(powerstat_params)

    if @powerstat.save
      redirect_to @powerstat
    else
      render 'new'
    end
  end

  def update
    @powerstat = Powerstat.find(params[:id])

    if @powerstat.update(powerstat_params)
      redirect_to @powerstat
    else
      render 'edit'
    end
  end

  def destroy
    @powerstat = Powerstat.find(params[:id])
    @powerstat.destroy

    redirect_to powerstats_path
  end

  private
    def powerstat_params
      params.require(:powerstat).permit(:location, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/powerstats_helper.rb
module PowerstatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LightDey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/Index.html.erb
<h1>Pages#Index</h1>
<p>Find me in app/views/pages/Index.html.erb</p>

app/views/powerstats/edit.html.erb
<h1>Editing article</h1>

<%= form_for :powerstat, url: powerstat_path(@powerstat), method: :patch do |f| %>
  <% if @powerstat.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@powerstat.errors.count, "error") %> prohibited
      this powerstat from being saved:</h2>
    <ul>
    <% @powerstat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', powerstats_path %>

app/views/powerstats/index.html.erb
<h1>Listing articles</h1>

<%= link_to 'New article', new_powerstat_path %>
<br />

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @powerstats.each do |powerstat| %>
    <tr>
      <td><%= powerstat.location %></td>
      <td><%= powerstat.address %></td>
      <td><%= link_to 'Show', powerstat_path(powerstat) %></td>
      <td><%= link_to 'Edit', edit_powerstat_path(powerstat) %></td>
      <td><%= link_to 'Destroy', powerstat_path(powerstat),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/powerstats/new.html.erb
<%= form_with scope: :powerstat, url: powerstats_path, local: true do |form| %>
  <p>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
  </p>

  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/powerstats/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @powerstat.location %>
</p>

<p>
  <strong>Text:</strong>
  <%= @powerstat.address %>
</p>

<%= link_to 'Back', powerstats_path %>